services:
  stream-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ad-astra-video/stream-server:latest
    container_name: byoc-stream-server
    env_file:
      - stream-server/.env
    volumes:
      - ./frontend/dist:/app/frontend/dist
    ports:
      - 4021:4021
    environment:
      - NODE_ENV=development
      - PORT=4021
    restart: unless-stopped